# Project information
site_name: 'USDS'
site_description: 'A group of libraries to help write Jetpack Compose apps.'
site_author: 'Google'
site_url: 'https://google.github.io/usds/'
edit_uri: 'tree/main/docs/'
remote_branch: gh-pages

docs_dir: docs



# Navigation
nav:
  - Overview: index.md
  - Thesis: thesis.md
  - Audit: audit.md
  - Blog:
      - Introduction: blog/index.md
      - Design Principles: blog/design.md
      - Tokenomics: blog/tokenomics.md
  - Protocol:
      - Architecture: protocol/architecture.md
      - Stability Mechanism: protocol/stability.md
  - Technical Reference:
      - Smart Contracts: technical/contracts.md
      - Security Model: technical/security.md
  - FAQ: faq.md
  - License: license.md

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'black'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
